export const PRODUCTS = [
  {
    id: 'nova',
    name: 'NOVA X',
    sub: 'Flagship Over-Ear',
    price: '$449',
    priceNum: 449,
    tag: 'BESTSELLER',
    rating: 4.9,
    reviewCount: '1.2k',
    category: 'Over-Ear · ANC',
    tagline: 'Where silence meets perfection. Active noise cancellation so deep, the world simply disappears.',
    soundDesc: 'Engineered with 40mm beryllium-coated drivers delivering a flat, reference-grade response from 5Hz to 40kHz — the full spectrum of human perception, and then some.',
    image: '/nova.png',
    accentColor: '#e8c97a',
    glowColor: '#c8a84a',
    colors: ['#1a1a1a', '#c8a84a', '#8b4513', '#2d4a6b'],
    colorNames: ['Midnight', 'Gold', 'Cognac', 'Navy'],
    colorImages: {
      '#1a1a1a': '/nova.png',
      '#c8a84a': '/nova_gold.png',
      '#8b4513': '/nova_cognac.png',
      '#2d4a6b': '/nova_navy.png',
    },
    specs: [
      { val: '40', unit: 'mm', label: 'Driver Size' },
      { val: '5-40k', unit: 'Hz', label: 'Frequency' },
      { val: '40', unit: 'dB', label: 'ANC Depth' },
      { val: '32', unit: 'h', label: 'Battery' },
    ],
    features: [
      { icon: '🧲', name: 'Beryllium Drivers', desc: 'Ultra-light, ultra-rigid for pristine highs', badge: 'Flagship' },
      { icon: '🔇', name: 'Active Noise Cancel', desc: 'Multi-point hybrid ANC with transparency mode', badge: '-40dB' },
      { icon: '📡', name: 'Spatial Audio', desc: 'Head-tracked 3D audio with motion sensors', badge: 'New' },
      { icon: '⚡', name: 'Fast Charge', desc: '10 min charge = 5 hours playback', badge: 'Quick' },
    ],
    review: '"The NOVA X sets a new benchmark for what a consumer headphone can achieve. The noise cancellation is genuinely eerie — and the soundstage rivals studio monitors we\'ve tested at three times the price."',
    reviewAuthor: '— AudiophileToday, 2024 Headphone of the Year',
    score: '9.8',
    geometry: 'icosahedron',
  },
  {
    id: 'pulse',
    name: 'PULSE',
    sub: 'Studio Monitor',
    price: '$299',
    priceNum: 299,
    tag: 'AUDIOPHILE',
    rating: 4.8,
    reviewCount: '860',
    category: 'Over-Ear · Open Back',
    tagline: 'Truth in every note. Open-back architecture delivers the soundstage of a concert hall, wherever you are.',
    soundDesc: 'Open acoustic architecture with 50mm planar-magnetic drivers. No coloration. No compromise. Just music, exactly as it was mixed.',
    image: '/pulse.png',
    accentColor: '#7eb8d4',
    glowColor: '#4a9abf',
    colors: ['#f5f5f0', '#7eb8d4', '#2d2d2d', '#8b7355'],
    colorNames: ['Pearl', 'Sky', 'Graphite', 'Walnut'],
    colorImages: {
      '#f5f5f0': '/pulse.png',
      '#7eb8d4': '/pulse_sky.png',
      '#2d2d2d': '/pulse_graphite.png',
      '#8b7355': '/pulse_walnut.png',
    },
    specs: [
      { val: '50', unit: 'mm', label: 'Driver Size' },
      { val: '10-50k', unit: 'Hz', label: 'Frequency' },
      { val: '32', unit: 'Ω', label: 'Impedance' },
      { val: '0.05', unit: '%', label: 'THD' },
    ],
    features: [
      { icon: '🎯', name: 'Planar Magnetic', desc: 'Uniform force across the entire diaphragm', badge: 'Studio' },
      { icon: '🌀', name: 'Open Back', desc: 'Natural, airy soundstage with zero fatigue', badge: 'Audiophile' },
      { icon: '🪵', name: 'Real Wood Cups', desc: 'Handcrafted walnut and mahogany options', badge: 'Premium' },
      { icon: '🔌', name: 'Balanced XLR', desc: '4-pin XLR + 6.35mm + 3.5mm included', badge: 'Pro' },
    ],
    review: '"We handed these to five professional mastering engineers. All five independently asked where they could buy a pair. That tells you everything you need to know about the PULSE."',
    reviewAuthor: '— StudioSound Magazine, Editor\'s Choice',
    score: '9.5',
    geometry: 'torus',
  },
  {
    id: 'arc',
    name: 'ARC',
    sub: 'Sport & Lifestyle',
    price: '$189',
    priceNum: 189,
    tag: 'NEW',
    rating: 4.7,
    reviewCount: '540',
    category: 'On-Ear · Wireless',
    tagline: 'Move freely. Hear boldly. Engineered for the ones who never stop — sweat-proof, drop-proof, and devastatingly good.',
    soundDesc: 'Custom-tuned 32mm dynamic drivers with a V-shaped acoustic signature. Punchy, energetic bass that hits as hard as your workout.',
    image: '/arc.png',
    accentColor: '#e05c3a',
    glowColor: '#c8402a',
    colors: ['#1a1a1a', '#e05c3a', '#f5f0e8', '#2d5a3d'],
    colorNames: ['Phantom', 'Ember', 'Chalk', 'Forest'],
    colorImages: {
      '#1a1a1a': '/arc_phantom.png',
      '#e05c3a': '/arc.png',
      '#f5f0e8': '/arc_chalk.png',
      '#2d5a3d': '/arc_forest.png',
    },
    specs: [
      { val: '32', unit: 'mm', label: 'Driver Size' },
      { val: '20-20k', unit: 'Hz', label: 'Frequency' },
      { val: 'IP67', unit: '', label: 'Water Rating' },
      { val: '60', unit: 'h', label: 'Battery' },
    ],
    features: [
      { icon: '💧', name: 'IP67 Waterproof', desc: 'Swim, sweat, rain — it handles everything', badge: 'Tough' },
      { icon: '🏃', name: 'Secure Fit', desc: 'Ergonomic arc frame with memory foam seals', badge: 'Sport' },
      { icon: '🎙️', name: '6 Mic Array', desc: 'ENC wind noise reduction for calls outdoors', badge: 'Clear' },
      { icon: '📶', name: 'Multipoint BT 5.3', desc: 'Connect two devices simultaneously', badge: 'Smart' },
    ],
    review: '"The ARC is the rare sports headphone that doesn\'t sacrifice sound for durability. The 60-hour battery is almost absurd. We\'ve been wearing these for two months and can\'t imagine going back."',
    reviewAuthor: '— GearLab, Best Sport Headphone 2024',
    score: '9.2',
    geometry: 'sphere',
  },
];
